=== alinbiju/WSD-Lab/Lab-3/pro.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="userid" type="xs:byte"/>
                            <xs:element name="username" type="xs:string"/>
                            <xs:element name="password" type="xs:string"/>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="email" type="xs:string"/>
                            <xs:element name="age" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>        
    </xs:element>
</xs:schema>

=== alinbiju/WSD-Lab/Lab-3/pro.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="pro.xsl" type="text/xsl"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pro.xsd">
    <user>
        <userid>101</userid>
        <username>sam</username>
        <password>1245</password>
        <name>Sam</name>
        <email>sam@gmail.com</email>
        <age>45</age>
    </user>
    <user>
        <userid>102</userid>
        <username>john</username>
        <password>25022</password>
        <name></name>
        <email>john@gmail.com</email>
        <age>25</age>
    </user>
    <user>
        <userid>103</userid>
        <username>mike</username>
        <password>2554</password>
        <name>Mike</name>
        <email>mike@gmail.com</email>
        <age>18</age>
    </user>
    <user>
        <userid>104</userid>
        <username>manuel</username>
        <password>87545</password>
        <name>Manuel</name>
        <email>man@gmail.com</email>
        <age>51</age>
    </user>

</users>
